# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-05 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20181205_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='foods',
        ),
        migrations.AddField(
            model_name='animal',
            name='enemy',
            field=models.ManyToManyField(related_name='_animal_enemy_+', to='animals.Animal'),
        ),
    ]
