# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-05 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_auto_20181205_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food', to='animals.Country'),
        ),
    ]
