# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-05 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_remove_food_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoo',
            name='animals',
            field=models.ManyToManyField(null=True, related_name='zoos', to='animals.Animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='enemy',
            field=models.ManyToManyField(null=True, related_name='_animal_enemy_+', to='animals.Animal'),
        ),
        migrations.AlterField(
            model_name='spiece',
            name='countries',
            field=models.ManyToManyField(null=True, related_name='spieces', to='animals.Country'),
        ),
        migrations.AlterField(
            model_name='spiece',
            name='foods',
            field=models.ManyToManyField(null=True, related_name='spieces', to='animals.Food'),
        ),
    ]
